name: Build pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build . -t jerilok/cpp-build-test:${{ github.sha }}
        docker run --name test_container jerilok/cpp-build-test:${{ github.sha }}
        docker cp test_container:/usr/src/app/coverage.info .
        docker cp test_container:/usr/src/app/out ./coverage_report

    - uses: actions/upload-artifact@v4
      with:
        retention-days: 1
        if-no-files-found: warn
        name: coverage-report
        path: coverage_report/

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        build-args: GIT_COMMIT=${{ github.sha }}
        tags: jerilok/cpp-build-test:${{ github.sha }}


